config/routes.rb
Rails.application.routes.draw do
  get 'invoice/index'
  get 'invoice/show'
  get 'orders/index'
  get 'orders/show'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: "home#show"
  #resources :games
  resources :genres
  resources :platforms

  resources :games do
    collection do
      get 'search'
    end
  end

  resources :shopping_cart#, only: %i[create edit destroy]
  get "/shopping_cart",   to: "shopping_cart#index"
  post "/shopping_cart/:id",   to: "shopping_cart#add_to_cart"

  resources :orders#, only: %i[create edit destroy]


  scope "/checkout" do
    post "create",  to: "checkout#create",  as: "checkout_create"
    get  "success", to: "checkout#success", as: "checkout_success"
    get  "cancel",  to: "checkout#cancel",  as: "checkout_cancel"
  end

  get "/home",            to: "home#show"
  get "/contact",         to: "contact#show"
  get "/about",           to: "about#show"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :game_genres
    has_many :game_platforms
    has_many :game_orders
    has_many :orders, through: :game_orders
    has_many :genres, through: :game_genres
    has_many :platforms, through: :game_platforms

    accepts_nested_attributes_for :game_genres, :game_platforms, allow_destroy: true


    validates :name, :price, :score, :rating, presence: true
    validates :price, :score, numericality: true

    paginates_per 20
end

app/models/game_genre.rb
class GameGenre < ApplicationRecord
  belongs_to :game
  belongs_to :genre
end

app/models/game_order.rb
class GameOrder < ApplicationRecord
  belongs_to :order
  belongs_to :game

  validates :product, :quantity, :price, presence: true
  validates :price, numericality: true
end

app/models/game_platform.rb
class GamePlatform < ApplicationRecord
  belongs_to :game
  belongs_to :platform
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :game_genres
    has_many :games, through: :game_genres

    validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :game_orders
end

app/models/platform.rb
class Platform < ApplicationRecord
    has_many :game_platforms
    has_many :games, through: :game_platforms

    validates :name, presence: true
end

app/models/province.rb
class Province < ApplicationRecord
    has_many :users

    validates :name, :total_tax, presence: true
    validates :total_tax, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :province
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: %i[ show edit update destroy ]

  # GET /genres or /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1 or /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres or /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: "Genre was successfully created." }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1 or /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: "Genre was successfully updated." }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1 or /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: "Genre was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def genre_params
      params.require(:genre).permit(:name, :description)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/genres/_form.html.erb
<%= form_with(model: genre) do |form| %>
  <% if genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
        <% genre.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/genres/_genre.html.erb
<div class="column is-one-third">
    <div class="card">
        <div class="card-content">
            <h3 class="title is-5"><%= link_to genre.name, genre %></h3>
            <br>
            <p><%= genre.description%></p>
        </div>
    </div>
</div>

app/views/genres/edit.html.erb
<h1>Editing Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Genre</h1>

<div class="columns is-multiline is-4">
  <%= render partial: 'genres/genre',
             collection: @genres,
             locals: { show_link: true } %>
</div>

<br>

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card-content">
  <h3 class="title is-5"><%= @genre.name %></h3>
  <br>
  <p><%= @genre.description%></p>
</div>

<div class="columns is-multiline is-4">
  <%= render partial: 'games/game',
             collection: @genre.games,
             locals: { show_link: true } %>
</div>