config/routes.rb
Rails.application.routes.draw do
  get 'invoice/index'
  get 'invoice/show'
  get 'orders/index'
  get 'orders/show'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: "home#show"
  #resources :games
  resources :genres
  resources :platforms

  resources :games do
    collection do
      get 'search'
    end
  end

  resources :shopping_cart#, only: %i[create edit destroy]
  get "/shopping_cart",   to: "shopping_cart#index"
  post "/shopping_cart/:id",   to: "shopping_cart#add_to_cart"

  resources :orders#, only: %i[create edit destroy]


  scope "/checkout" do
    post "create",  to: "checkout#create",  as: "checkout_create"
    get  "success", to: "checkout#success", as: "checkout_success"
    get  "cancel",  to: "checkout#cancel",  as: "checkout_cancel"
  end

  get "/home",            to: "home#show"
  get "/contact",         to: "contact#show"
  get "/about",           to: "about#show"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :game_genres
    has_many :game_platforms
    has_many :game_orders
    has_many :orders, through: :game_orders
    has_many :genres, through: :game_genres
    has_many :platforms, through: :game_platforms

    accepts_nested_attributes_for :game_genres, :game_platforms, allow_destroy: true


    validates :name, :price, :score, :rating, presence: true
    validates :price, :score, numericality: true

    paginates_per 20
end

app/models/game_genre.rb
class GameGenre < ApplicationRecord
  belongs_to :game
  belongs_to :genre
end

app/models/game_order.rb
class GameOrder < ApplicationRecord
  belongs_to :order
  belongs_to :game

  validates :product, :quantity, :price, presence: true
  validates :price, numericality: true
end

app/models/game_platform.rb
class GamePlatform < ApplicationRecord
  belongs_to :game
  belongs_to :platform
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :game_genres
    has_many :games, through: :game_genres

    validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :game_orders
end

app/models/platform.rb
class Platform < ApplicationRecord
    has_many :game_platforms
    has_many :games, through: :game_platforms

    validates :name, presence: true
end

app/models/province.rb
class Province < ApplicationRecord
    has_many :users

    validates :name, :total_tax, presence: true
    validates :total_tax, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :province
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  before_action :set_platform, only: %i[ show edit update destroy ]

  # GET /platforms or /platforms.json
  def index
    @platforms = Platform.all
  end

  # GET /platforms/1 or /platforms/1.json
  def show
  end

  # GET /platforms/new
  def new
    @platform = Platform.new
  end

  # GET /platforms/1/edit
  def edit
  end

  # POST /platforms or /platforms.json
  def create
    @platform = Platform.new(platform_params)

    respond_to do |format|
      if @platform.save
        format.html { redirect_to @platform, notice: "Platform was successfully created." }
        format.json { render :show, status: :created, location: @platform }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /platforms/1 or /platforms/1.json
  def update
    respond_to do |format|
      if @platform.update(platform_params)
        format.html { redirect_to @platform, notice: "Platform was successfully updated." }
        format.json { render :show, status: :ok, location: @platform }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /platforms/1 or /platforms/1.json
  def destroy
    @platform.destroy
    respond_to do |format|
      format.html { redirect_to platforms_url, notice: "Platform was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_platform
      @platform = Platform.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def platform_params
      params.require(:platform).permit(:name, :description)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/platforms/_form.html.erb
<%= form_with(model: platform) do |form| %>
  <% if platform.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(platform.errors.count, "error") %> prohibited this platform from being saved:</h2>

      <ul>
        <% platform.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/platforms/_platform.html.erb
<div class="column is-one-fifth">
    <div class="card">
        <div class="card-content">
            <h3 class="title is-5"><%= link_to platform.name, platform %></h3>
            <br>
            <p><%= platform.description%></p>
        </div>
    </div>
</div>

app/views/platforms/edit.html.erb
<h1>Editing Platform</h1>

<%= render 'form', platform: @platform %>

<%= link_to 'Show', @platform %> |
<%= link_to 'Back', platforms_path %>

app/views/platforms/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Platforms</h1>

<div class="columns is-multiline is-4">
  <%= render partial: 'platforms/platform',
             collection: @platforms,
             locals: { show_link: true } %>
</div>

<br>

app/views/platforms/new.html.erb
<h1>New Platform</h1>

<%= render 'form', platform: @platform %>

<%= link_to 'Back', platforms_path %>

app/views/platforms/show.html.erb
<div class="card">
  <div class="card-content">
      <h3 class="title is-5"><%= @platform.name%></h3>
      <br>
      <p><%= @platform.description%></p>
  </div>
</div>

<div class="columns is-multiline is-4">
  <%= render partial: 'games/game',
             collection: @platform.games,
             locals: { show_link: true } %>
</div>