config/routes.rb
Rails.application.routes.draw do
  get 'invoice/index'
  get 'invoice/show'
  get 'orders/index'
  get 'orders/show'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: "home#show"
  #resources :games
  resources :genres
  resources :platforms

  resources :games do
    collection do
      get 'search'
    end
  end

  resources :shopping_cart#, only: %i[create edit destroy]
  get "/shopping_cart",   to: "shopping_cart#index"
  post "/shopping_cart/:id",   to: "shopping_cart#add_to_cart"

  resources :orders#, only: %i[create edit destroy]


  scope "/checkout" do
    post "create",  to: "checkout#create",  as: "checkout_create"
    get  "success", to: "checkout#success", as: "checkout_success"
    get  "cancel",  to: "checkout#cancel",  as: "checkout_cancel"
  end

  get "/home",            to: "home#show"
  get "/contact",         to: "contact#show"
  get "/about",           to: "about#show"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :game_genres
    has_many :game_platforms
    has_many :game_orders
    has_many :orders, through: :game_orders
    has_many :genres, through: :game_genres
    has_many :platforms, through: :game_platforms

    accepts_nested_attributes_for :game_genres, :game_platforms, allow_destroy: true


    validates :name, :price, :score, :rating, presence: true
    validates :price, :score, numericality: true

    paginates_per 20
end

app/models/game_genre.rb
class GameGenre < ApplicationRecord
  belongs_to :game
  belongs_to :genre
end

app/models/game_order.rb
class GameOrder < ApplicationRecord
  belongs_to :order
  belongs_to :game

  validates :product, :quantity, :price, presence: true
  validates :price, numericality: true
end

app/models/game_platform.rb
class GamePlatform < ApplicationRecord
  belongs_to :game
  belongs_to :platform
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :game_genres
    has_many :games, through: :game_genres

    validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :game_orders
end

app/models/platform.rb
class Platform < ApplicationRecord
    has_many :game_platforms
    has_many :games, through: :game_platforms

    validates :name, presence: true
end

app/models/province.rb
class Province < ApplicationRecord
    has_many :users

    validates :name, :total_tax, presence: true
    validates :total_tax, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :province
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]

  # GET /games or /games.json
  def index
    @games = Game.order(:name).page(params[:page])
  end

  # GET /games/1 or /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    search_genre = params[:genre]
    search_platform = params[:platform]

    if search_genre == ""
      genre = Game.all
    else
      genre = Game.joins(game_genres: :genre).where("Genres.id LIKE ?", search_genre)
    end

    if search_platform == ""
      platform = genre
    else
      platform = genre.joins(game_platforms: :platform).where("Platforms.id LIKE ?", search_platform)
    end

    #search = Game.where("Games.name LIKE ? OR Games.description LIKE ?", wildcard_search, wildcard_search).order(:name).page(params[:page])
    #genre = Game.joins(game_genres: :genre).where("Genres.id LIKE ?", search_genre)
    #platform = genre.joins(game_platforms: :platforms).where("Platforms.id LIKE ?", search_platform)
    @games = platform.where("Games.name LIKE ? OR Games.description LIKE ?", wildcard_search, wildcard_search).order(:name).page(params[:page])
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:name, :description, :price, :score, :rating)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.text_field :score %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div class="column is-one-quarter">
    <div class="card">
        <div class="card-content">
            <h3 class="title is-5"><%= link_to game.name, game %></h3>
            <p>Score:       <%= game.score%></p>
            <p>Rating:      <%= game.rating%></p>
            <p>Price:       <%= number_to_currency game.price%></p>
            <p>Genres:      <% game.genres.each do |genre| %> <%= link_to genre.name, genre %><% end %></p>
            <p>Platforms:   <% game.platforms.each do |platform| %> <%= link_to platform.name, platform %><% end %></p>
            <br>
            <p><%= game.description%></p>


            <%= button_to "Add to cart", shopping_cart_path(game.id), method: :post %>

        </div>
    </div>
</div>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Games</h1>

<div class="columns is-multiline is-4">
  <%= render partial: 'games/game',
             collection: @games,
             locals: { show_link: true } %>
</div>

<%= paginate @games %>


<br>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/search.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Games</h1>

<%= form_with(url: search_games_path, method: :get, local: true) do |form| %>
    <div class="field is-grouped mb-5">
        <div class="control is-expanded">
            <%= text_field_tag(:keywords, nil, class: "input", placeholder: 'Search Games', size: "200") %>
        </div>
        <%= form.select :genre, Genre.all.collect {|g| [g.name, g.id]}, :include_blank => true, :multiple => "multiple" %>
        <%= form.select :platform, Platform.all.collect {|p| [p.name, p.id]}, :include_blank => true, :multiple => "multiple" %>
        <div class="control">
            <%= submit_tag("Search", class: "button is-primary") %>
        </div>
    </div>
<% end %>

<div class="columns is-multiline is-4">
  <%= render partial: 'games/game',
             collection: @games,
             locals: { show_link: true } %>
</div>

<%= paginate @games %>

<br>

app/views/games/show.html.erb
<h1 class="title">Game</h1>

<div class="card-content">
  <h3 class="title is-5"><%= @game.name%></h3>
  <p>Score:       <%= @game.score%></p>
  <p>Rating:      <%= @game.rating%></p>
  <p>Price:       $<%= @game.price%></p>
  <p>Genres:      <% @game.genres.each do |genre| %> <%= link_to genre.name, genre %><% end %></p>
  <p>Platforms:   <% @game.platforms.each do |platform| %> <%= link_to platform.name, platform %><% end %></p>
  <br>
  <p><%= @game.description%></p>
</div>